/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistem;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import koneksi.conek;
/**
 *
 * @author Roffi
 */
public class FormData extends javax.swing.JFrame {
    Connection Con;
    ResultSet Rslt;
    Statement stm;
    
    Boolean edit=false;
    ResultSetMetaData meta;
    private Object[][] dataTable = null;
    private String[] header ={"No","Data X","Data Y"};
    
    int jumlahdatatabel = 0;
    
    public FormData() {
        initComponents();
        open_db();
        baca_data();
        setdisable();
        setkosong();
    }
    
    private void open_db()
    {       
        try{
            conek kon = new conek();
            Con = conek.GetConnection();
            System.out.println("Berhasil koneksi dengan database");
        }catch (SQLException e) {
            System.out.println("Error : "+e);
            }
    }
    
    private void setdisable(){
        simpan_btn.setEnabled(false);
        input_data_x.setEnabled(false);
        input_data_y.setEnabled(false);
    }
    
    private void setField(){
        int row=tabeldataku.getSelectedRow();
        
        String nomor = Integer.toString((Integer)tabeldataku.getValueAt(row, 0));
        input_nomor.setText(nomor);
        
        String datax1 = Integer.toString((Integer)tabeldataku.getValueAt(row, 1));
        input_data_x.setText(datax1);
        
        String datay1 = Integer.toString((Integer)tabeldataku.getValueAt(row, 2));
        input_data_y.setText(datay1);
    }
    
    private void baca_data(){
        try{
            stm = Con.createStatement();
            Rslt = stm.executeQuery("select * from tbcacat");
            meta = Rslt.getMetaData();
            int col = meta.getColumnCount();
            int baris = 0;
            jumlahdatatabel = 0;
            while(Rslt.next()) {
                
                baris = Rslt.getRow();
                jumlahdatatabel++;
            }
            dataTable = new Object[baris][col];
            int x = 0;
            Rslt.beforeFirst();
            while(Rslt.next()) {
                dataTable[x][0] = Rslt.getInt("tanggal");
                dataTable[x][1] = Rslt.getInt("rata_suhu_ruangan");
                dataTable[x][2] = Rslt.getInt("jumlah_cacat");
                x++;
            }
            tabeldataku.setModel(new DefaultTableModel(dataTable,header));
            jumlahdatatabel=jumlahdatatabel +1;
            input_nomor.setText(""+jumlahdatatabel);
        }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void setkosong(){
        input_data_x.setText("");
        input_data_y.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldataku = new javax.swing.JTable();
        simpan_btn = new javax.swing.JButton();
        edit_btn = new javax.swing.JButton();
        hapus_btn = new javax.swing.JButton();
        kembali_menuutama = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        input_data_x = new javax.swing.JTextField();
        input_data_y = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        input_nomor = new javax.swing.JTextField();
        tambah_btn = new javax.swing.JButton();
        hapussemua_btn1 = new javax.swing.JButton();

        setTitle("Data Regresi Linier Sederhana");

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("DATA REGRESI LINIER SEDERHANA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabeldataku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Data X", "Data Y"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabeldataku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldatakuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldataku);

        simpan_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Roffi\\Documents\\NetBeansProjects\\Teknik Estimasi Regresi Sederhana\\src\\icon\\save all.png")); // NOI18N
        simpan_btn.setText("Simpan");
        simpan_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_btnActionPerformed(evt);
            }
        });

        edit_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Roffi\\Documents\\NetBeansProjects\\Teknik Estimasi Regresi Sederhana\\src\\icon\\edit.png")); // NOI18N
        edit_btn.setText("Edit");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });

        hapus_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Roffi\\Documents\\NetBeansProjects\\Teknik Estimasi Regresi Sederhana\\src\\icon\\delete.png")); // NOI18N
        hapus_btn.setText("Hapus");
        hapus_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus_btnActionPerformed(evt);
            }
        });

        kembali_menuutama.setText("Menu Utama");
        kembali_menuutama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali_menuutamaActionPerformed(evt);
            }
        });

        jLabel2.setText("Data X");

        jLabel3.setText("Data Y");

        jLabel4.setText("No.");

        input_nomor.setEditable(false);
        input_nomor.setEnabled(false);

        tambah_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Roffi\\Documents\\NetBeansProjects\\Teknik Estimasi Regresi Sederhana\\src\\icon\\add.png")); // NOI18N
        tambah_btn.setText("Tambah");
        tambah_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_btnActionPerformed(evt);
            }
        });

        hapussemua_btn1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Roffi\\Documents\\NetBeansProjects\\Teknik Estimasi Regresi Sederhana\\src\\icon\\delete.png")); // NOI18N
        hapussemua_btn1.setText("Clear All");
        hapussemua_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapussemua_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tambah_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapus_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hapussemua_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kembali_menuutama, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(input_data_x, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(input_nomor, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(simpan_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(input_data_y, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_nomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(input_data_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(input_data_y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(simpan_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapus_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kembali_menuutama, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambah_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapussemua_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpan_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_btnActionPerformed
        int no         = jumlahdatatabel;
        int noalias    = Integer.parseInt(input_nomor.getText());
        int datax1     = Integer.parseInt(input_data_x.getText());
        int datay1     = Integer.parseInt(input_data_y.getText());
        
        try{
            stm = Con.createStatement();
            if(edit==true){
                stm.executeUpdate("UPDATE tbcacat SET rata_suhu_ruangan="+datax1+", jumlah_cacat="+datay1+" WHERE tanggal="+noalias+" ");                
                edit=false;
            }else{
                stm.executeUpdate("INSERT INTO tbcacat VALUES ("+no+","+datax1+","+datay1+") ");
            }
            tabeldataku.setModel(new DefaultTableModel(dataTable,header));
            JOptionPane.showMessageDialog(null, "simpan berhasil");
            baca_data();
            setkosong();
            setdisable();
            tambah_btn.setEnabled(true);
        }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_simpan_btnActionPerformed

    private void hapus_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus_btnActionPerformed
        try{
            String  sql="delete from tbcacat where tanggal=" + Integer.parseInt(input_nomor.getText()) + "";
            stm.executeUpdate(sql);
            setkosong();
            baca_data();
        }catch(SQLException e)  {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_hapus_btnActionPerformed

    private void tabeldatakuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldatakuMouseClicked
        setField();
    }//GEN-LAST:event_tabeldatakuMouseClicked

    private void kembali_menuutamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali_menuutamaActionPerformed
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembali_menuutamaActionPerformed

    private void tambah_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_btnActionPerformed
        simpan_btn.setEnabled(true);
        input_data_x.setEnabled(true);
        input_data_y.setEnabled(true);
        tambah_btn.setEnabled(false);
    }//GEN-LAST:event_tambah_btnActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        edit=true;
        simpan_btn.setEnabled(true);
        input_data_x.setEnabled(true);
        input_data_y.setEnabled(true);
    }//GEN-LAST:event_edit_btnActionPerformed

    private void hapussemua_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapussemua_btn1ActionPerformed
        try{
            String  sql="delete from tbcacat ";
            stm.executeUpdate(sql);
            setkosong();
            baca_data();
        }catch(SQLException e)  {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_hapussemua_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton edit_btn;
    private javax.swing.JButton hapus_btn;
    private javax.swing.JButton hapussemua_btn1;
    private javax.swing.JTextField input_data_x;
    private javax.swing.JTextField input_data_y;
    private javax.swing.JTextField input_nomor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembali_menuutama;
    private javax.swing.JButton simpan_btn;
    private javax.swing.JTable tabeldataku;
    private javax.swing.JButton tambah_btn;
    // End of variables declaration//GEN-END:variables
}
