/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistem;

/**
 *
 * @author Roffi
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_hitungregresi = new javax.swing.JMenu();
        menu_hitungregresi1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menu_aturdata = new javax.swing.JMenu();
        menu_data_regresilinierberganda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Regresi Linier");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1339, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 153, 51));

        jMenu1.setText("File");

        menu_hitungregresi.setText("Regresi Linier Sederhana");
        menu_hitungregresi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_hitungregresiMouseClicked(evt);
            }
        });
        jMenu1.add(menu_hitungregresi);

        menu_hitungregresi1.setText("Regresi Linier Ganda");
        menu_hitungregresi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_hitungregresi1MouseClicked(evt);
            }
        });
        jMenu1.add(menu_hitungregresi1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        menu_aturdata.setText("Data Regresi Linier Sederhana");
        menu_aturdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_aturdataMouseClicked(evt);
            }
        });
        jMenu2.add(menu_aturdata);

        menu_data_regresilinierberganda.setText("Data Regresi Linier Ganda");
        menu_data_regresilinierberganda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_data_regresilinierbergandaMouseClicked(evt);
            }
        });
        jMenu2.add(menu_data_regresilinierberganda);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_hitungregresiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_hitungregresiMouseClicked
        new Regresi().setVisible(true);
    }//GEN-LAST:event_menu_hitungregresiMouseClicked

    private void menu_aturdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_aturdataMouseClicked
        new FormData().setVisible(true);
    }//GEN-LAST:event_menu_aturdataMouseClicked

    private void menu_hitungregresi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_hitungregresi1MouseClicked
        new RegresiLinierGanda().setVisible(true);
    }//GEN-LAST:event_menu_hitungregresi1MouseClicked

    private void menu_data_regresilinierbergandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_data_regresilinierbergandaMouseClicked
        new FormDataRegresiLinierGanda().setVisible(true);
    }//GEN-LAST:event_menu_data_regresilinierbergandaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu_aturdata;
    private javax.swing.JMenu menu_data_regresilinierberganda;
    private javax.swing.JMenu menu_hitungregresi;
    private javax.swing.JMenu menu_hitungregresi1;
    // End of variables declaration//GEN-END:variables
}
